### PR TITLE
Add 3 API and update app.py

### PR DESCRIPTION
**Pull request by ssTKuo**
完成Part 1-2: Complete Attraction APIs任務:
1.撰寫Attration 2支API (取得景點資料表、根據景點編號取得景點資料)
2.撰寫MRT Station 1支API (根據景點編號取得景點資料)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where are your online URLs? What's your name?

**Comment by ssTKuo** [comment]
老師抱歉，我搞錯提交順序了，另app.py的程式碼我有發現一些小錯誤，待修正後我會一併補上URLs，到時候再tag老師檢查!  謝謝~

**Comment by ssTKuo** [comment]
@cwpeng

**Comment by ssTKuo** [comment]
@cwpeng 
老師好，我已完成本週任務，再煩請老師確認，謝謝。

學員姓名: 郭昭廷
http://13.239.94.255:8000/api/attractions?page=1
http://13.239.94.255:8000/api/attractions?page=0&keyword=劍潭
http://13.239.94.255:8000/api/attractions?page=0&keyword=北
http://13.239.94.255:8000/api/attraction/10
http://13.239.94.255:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but we just use keyword for filtering attraction data by MRT or name.

**Comment by ssTKuo** [comment]
老師好，我已修正app.py中程式碼(如下所示)，並更新佈署至EC2，再煩請老師檢查，謝謝!
`if keyword:
            query = ("""
                SELECT * FROM attractions 
                WHERE name LIKE %s OR mrt LIKE %s
                LIMIT %s OFFSET %s
            """)`

**Review by cwpeng — CHANGES_REQUESTED** [review]
nextPage field of the last page should be null. For example, nextPage field of http://13.239.94.255:8000/api/attractions?page=1&keyword=%E5%8C%97 should be null.

**Comment by ssTKuo** [comment]
老師好，已修正"nextPage field of the last page should be null"問題，再請老師確認了，謝謝!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
